Fix problem caused by np.arrays in global space
The errors was in find_global_name and was:
  ValueError: The truth value of an array with more than one element is ambiguous.
  Use a.any() or a.all()